backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: content/media
public_folder: content
collections:
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - name: "general"
        label: "Site Settings"
        file: "data.ndtl"
        description: "General Site Settings"
        fields:
          - { label: Text, name: text, required: true, widget: string }
